server.port=8080

auth0.issuer-uri=${AUTH0_ISSUER_URI:}
auth0.audience=${AUTH0_AUDIENCE:}

openweather.api-key=${OPENWEATHER_API_KEY:}
openweather.base-url=https://api.openweathermap.org/data/2.5/weather
openweather.cache-ttl-minutes=5

logging.level.com.fidenz.weathercomfort=DEBUG
server.error.include-message=always
server.error.include-stacktrace=always